export const SOLO_SAVINGS_TYPES = {
    TOTAL_SAVINGS: 'savings/TOTAL_SOLO_SAVINGS',
    ALL_SOLO_SAVINGS: 'savings/ALL_SOLO_SAVINGS',
    ALL_BUDDY_SAVINGS: 'buddy/ALL_BUDDY_SAVINGS',
    ALL_SAVINGS_CHALLENGE: 'challenge/ALL_SAVINGS_CHALLENGE',
    SET_SOLO_SAVINGS: 'savings/SET_SOLO_SAVINGS',
    UPDATE_SAVINGS: 'savings/UPDATE_SAVINGS'
}