import {StyleSheet, Dimensions} from 'react-native';
const {width} = Dimensions.get('window');

const designs = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F7F8FD',
    paddingTop: 20,
    // paddingLeft: 16,
    // paddingRight: 16,
    padding: 15,
    fontFamily: 'CircularStd',
  },
  header: {
    marginTop: 22,
    backgroundColor: '#2A286A',
    width: '100%',
    height: 60,
    borderTopLeftRadius: 50,
    borderTopRightRadius: 100,
    borderBottomRightRadius: 100,
    paddingTop: 12,
    paddingLeft: 20,
  },
  boldText: {
    fontSize: 16,
    lineHeight: 23,
    color: '#2A286A',
    fontFamily: 'CircularStd',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  textInput: {
    width: '100%',
    // height: 70,
    padding: 15,
    paddingHorizontal: 20,
    marginTop: 13,
    backgroundColor: 'white',
    borderRadius: 10,
    borderColor: '#EAEAEA',
    borderWidth: 1,
  },
  options: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 13,
  },
  button: {
    width: '100%',
    padding: 15,
    // height: 70,
    borderRadius: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    opacity: 1,
    backgroundColor: '#00DC99',
    marginTop: 60,
    marginLeft: 'auto',
    marginRight: 'auto',
    marginBottom: 20,
    elevation: 2,
  },
  summaryBox: {
    // height: 400,
    width: '100%',
    borderRadius: 20,
    backgroundColor: '#2A286A',
    marginTop: 15,
    padding: 15,
  },
  whiteBox: {
    width: '100%',
    // height: 66,
    borderRadius: 10,
    backgroundColor: 'white',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 27,
    overflow: 'hidden',
  },
  data: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    // justifyContent: 'space-between',
    marginTop: 20,
    paddingLeft: 6,
    paddingRight: 6,
  },
  key: {
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 15,
    color: 'white',
  },
  value: {
    fontSize: 14,
    fontWeight: 'bold',
    lineHeight: 20,
    color: 'white',
    marginTop: 2,
    // marginLeft: 5,
  },
  creditCard: {
    width: 365,
    height: 51,
    borderRadius: 10,
    backgroundColor: 'white',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#EAEAEA',
    marginTop: 26,
    padding: 19,
  },
  modal: {
    flex: 1,
    justifyContent: 'center',
    // alignItems: 'center',
    fontFamily: 'Circular Std',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    paddingLeft: 16,
    paddingRight: 16,
  },
  successModal: {
    backgroundColor: 'white',
    borderRadius: 16,
    height: 400,
    padding: 23,
  },
  soloSavingCard: {
    width: 380,
    height: 180,
    marginTop: 12,
    elevation: 6,
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  fadedBottom: {
    backgroundColor: '#9D98EC',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 16,
    height: 58,
    borderBottomRightRadius: 20,
    borderBottomLeftRadius: 20,
    padding: 26,
  },
  circularProgress: {
    width: 97,
    height: 97,
    zIndex: 9,
    position: 'relative',
    top: 25,
    left: 20,
  },
  whiteCard: {
    width: 163,
    height: 150,
    borderRadius: 15,
    backgroundColor: 'white',
    padding: 17,
  },
  displayFlex: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 55,
    marginLeft: 16,
    marginRight: 16,
  },
  transactions: {
    marginTop: 16,
    backgroundColor: 'white',
    height: 306,
    width: width,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 16,
  },
  transactionTab: {
    width: 127,
    height: 32,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dataInfo: {
    width: '50%',
    marginTop: 20,
    // borderWidth: 1,
  },
});

export default designs;
