require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'kwaba_mobile_app' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNFS', :path => '../node_modules/react-native-fs'


  target 'Kwaba_mobile_appTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # use_flipper!({ 'Flipper' => '0.74.0' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'kwaba_mobile_app-tvOS' do
  # Pods for kwaba_mobile_app-tvOS

  target 'kwaba_mobile_app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
