import {StyleSheet, Dimensions} from 'react-native';
import {COLORS} from '../../util';

const widthTouse = Dimensions.get('window').width;

const designs = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F7F8FD',
    fontFamily: 'CircularStd',
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  btn: {
    padding: 15,
    borderRadius: 10,
    marginTop: 10,
    fontSize: 14,
    fontFamily: 'CircularStd-Medium',
    fontWeight: '600',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    // elevation: 1,
  },
  textField: {
    borderRadius: 5,
    backgroundColor: '#FFFFFF',
    borderColor: '#EFEFEF',
    borderWidth: 1,
    marginTop: 10,
    width: '100%',
    paddingVertical: 15,
    paddingHorizontal: 20,
  },
  customInput: {
    borderRadius: 5,
    backgroundColor: '#FFFFFF',
    borderColor: '#EFEFEF',
    borderWidth: 1,
    marginTop: 10,

    width: '100%',
    position: 'relative',
  },
  image: {
    width: 50,
    height: 50,
  },
  heading: {
    color: '#2A286A',
    fontFamily: 'CircularStd',
    fontSize: 16,
    fontWeight: 'bold',
    lineHeight: 30,
    marginTop: 10,
  },
  body: {
    color: '#2A286A',
    fontFamily: 'CircularStd',
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 20,
  },
  codeInput: {
    width: 60,
    height: 60,
    borderRadius: 5,
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#46596950',
    fontSize: 18,
    textAlign: 'center',
    fontWeight: '900',
    color: 'black',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  codeInputContainer: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 20,
    paddingHorizontal: 40,
  },
  counter: {
    width: 80,
    height: 27,
    backgroundColor: '#9D98EC',
    borderRadius: 14,
    marginTop: 30,
    marginLeft: 'auto',
    marginRight: 'auto',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fingerPrint: {
    backgroundColor: 'white',
    width: 68,
    height: 70,
    borderRadius: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 15,
    color: '#BFBFBF',
  },
  errorText: {
    fontSize: 10,
    color: '#f00000',
    marginLeft: 5,
  },
  errorInput: {
    borderColor: '#f0000050',
  },

  cellText: {
    fontSize: 18,
    textAlign: 'center',
    fontWeight: 'bold',
    color: '#465969',
  },
  focusCell: {
    borderColor: '#00DC99',
  },
  headline: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.primary,
    marginTop: 10,
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 12,
    color: COLORS.dark,
    lineHeight: 20,
  },
  contentText: {
    paddingLeft: 20,
  },
});
export default designs;
