import {StyleSheet, Dimensions} from 'react-native';

const widthTouse = Dimensions.get('window').width;

const designs = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F7F8FD',
    fontFamily: 'CircularStd',
    padding: 20,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  btn: {
    // height: 70,
    padding: 15,
    borderRadius: 10,
    marginTop: 20,
    fontSize: 14,
    fontFamily: 'CircularStd-Medium',
    fontWeight: '600',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    // marginLeft: 16,
    // marginRight: 16,
    elevation: 1,
  },
  textField: {
    // height: 70,
    borderRadius: 5,
    backgroundColor: '#FFFFFF',
    borderColor: '#EFEFEF',
    borderWidth: 1,
    marginTop: 10,
    // paddingLeft: 22,
    // width: '100%',
    // alignSelf: 'center',
    width: '100%',
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 12,
    paddingBottom: 12,
  },
  customInput: {
    // height: 70,
    borderRadius: 5,
    backgroundColor: '#FFFFFF',
    borderColor: '#EFEFEF',
    borderWidth: 1,
    marginTop: 10,
    // padding: 10,
    // paddingLeft: 22,
    // paddingRight: 19,
    // display: 'flex',
    // flexDirection: 'row',
    // alignItems: 'center',
    // justifyContent: 'space-between',
    // width: widthTouse,
    // marginLeft: 16,

    width: '100%',
    // borderWidth: 1,
    position: 'relative',
  },
  image: {
    width: 129,
    height: 30,
    // marginLeft: 16,
    marginTop: 59,
  },
  heading: {
    color: '#2A286A',
    fontFamily: 'CircularStd',
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 30,
    marginLeft: 32,
    marginTop: 40,
  },
  body: {
    color: '#BFBFBF',
    fontFamily: 'CircularStd',
    fontSize: 14,
    fontWeight: '500',
    marginTop: 4,
    marginLeft: 32,
    lineHeight: 30,
  },
  codeInput: {
    width: 70,
    height: 70,
    borderRadius: 10,
    backgroundColor: 'white',
    borderColor: '#EFEFEF',
    borderWidth: 1,
    fontSize: 18,
    textAlign: 'center',
    fontWeight: '900',
    elevation: 1,
    color: 'black',
  },
  codeInputContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginLeft: 31,
    marginRight: 31,
    marginTop: 15,
  },
  counter: {
    width: 80,
    height: 27,
    backgroundColor: '#9D98EC',
    borderRadius: 14,
    marginTop: 52,
    marginLeft: 'auto',
    marginRight: 'auto',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fingerPrint: {
    backgroundColor: 'white',
    width: 68,
    height: 70,
    borderRadius: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 15,
    color: '#BFBFBF',
  },
});
export default designs;
