import {StyleSheet, Dimensions} from 'react-native';

const widthTouse = Dimensions.get('window').width;
const designs = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'baseline',
    backgroundColor: '#F7F8FD',
    justifyContent: 'center',
    // paddingTop: 200,
    // borderColor: '#f00',
    // borderStyle: 'solid',
    borderWidth: 1,
    position: 'relative',
  },
  image: {
    width: 100,
    height: 100,
    position: 'absolute',
    left: '50%',
    top: 0,
    zIndex: 2,
    transform: [{translateX: -50}],
    // height: 113,
    // marginLeft: 'auto',
    // marginRight: 'auto',
    resizeMode: 'contain',
    // borderColor: '#f00',
    borderWidth: 1,
  },
  bgImage: {
    width: '100%',
    height: '100%',
    bottom: 0,
    position: 'absolute',
    resizeMode: 'center',

    justifyContent: 'flex-end',

    // borderColor: '#f0f',
    // borderWidth: 1,
  },
  bgImageContainer: {
    width: '100%',
    height: '90%',
    bottom: 0,
    position: 'absolute',
    resizeMode: 'stretch',
    // borderColor: '#f00',
    // borderWidth: 1,
    // opacity: 0,
  },
  innerView: {
    display: 'flex',
    flexDirection: 'row',
    marginLeft: 31,
    marginRight: 20,
    marginTop: 128,
    justifyContent: 'space-between',
    // alignItems: 'center',
  },
  button: {
    height: 61,
    width: 61,
    borderRadius: 50,
    // opacity: 0.7,
    // backgroundColor: '#00000000',
    backgroundColor: 'rgba(255,255,255,.1)',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#ffffff30',
    borderWidth: 3,
    // backdropFilter: 1,
  },
  arrowFwd: {
    width: '100%',
    height: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    // backgroundColor: 'red',
  },
  bigText: {
    // textAlign: 'left',
    color: '#ffff',
  },
  smallText: {
    color: '#ffff',
    fontSize: 14,
    marginTop: 5,
    // textAlign: 'left',
  },
  getStartedBtn: {
    width: widthTouse * 0.9,
    height: 60,
    borderRadius: 10,
    backgroundColor: '#ffff',
    // marginLeft: 16,
    // marginRight: 16,
    // marginBottom: 50,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: '#2A286A',
    fontFamily: 'Poppins-Medium',
    fontWeight: '600',
    fontSize: 12,
  },
  linkContainer: {
    marginTop: 20,
    marginRight: 16,
    marginLeft: 16,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    fontFamily: 'Poppins-Medium',
    fontSize: 14,
    fontWeight: '600',
  },

  imageBG: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    resizeMode: 'stretch',
  },
});

export default designs;
