export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SOLO_SAVING = 'SOLO_SAVING';
export const GET_SOLO_SAVINGS = 'GET_SOLO_SAVINGS';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_MAX_LOAN_CAP = 'GET_MAX_LOAN_CAP';
export const GET_BUDDY_SAVINGS = 'GET_BUDDY_SAVINGS';
export const GET_ONE_BUDDY_SAVINGS = 'GET_ONE_BUDDY_SAVINGS';
export const GET_ONE_SOLO_SAVINGS = 'GET_ONE_SOLO_SAVINGS';
export const GET_ONE_SOLO_SAVINGS_TRANSACTION =
  'GET_ONE_SOLO_SAVINGS_TRANSACTION';
export const GET_BANK_ACCOUNTS = 'GET_BANK_ACCOUNTS';
export const GET_BANK_FROM_STORAGE = 'GET_BANK_FROM_STORAGE';
export const GET_BILLS_SERVICES = 'GET_BILLS_SERVICES';
export const GET_BILLS_CATEGORY = 'GET_BILLS_CATEGORY';
export const GET_AIRTIME_BILL_TRANS = 'GET_AIRTIME_BILL_TRANS';

export const GET_AIRTIME = 'GET_AIRTIME';

export const GET_USER_WALLET = 'GET_USER_WALLET';
export const GET_USER_WALLET_TRANSACTIONS = 'GET_USER_WALLET_TRANSACTIONS';

export const SAVINGS_CHALLENGE_LIST = 'SAVINGS_CHALLENGE_LIST'
