export const SAVINGS_CHALLENGE_TYPES = {
    ALL_SAVINGS_CHALLENGE: 'savings/ALL_SAVINGS_CHALLENGE',
    SET_SAVINGS_CHELLENGE: 'savings/SET_SAVINGS_CHELLENGE',
    UPDATE_SAVINGS_CHALLENGE: 'savings/UPDATE_SAVINGS_CHALLENGE'
}